### PR TITLE
make electro static example work with gallery

### PR DESCRIPTION
**Pull request by SimonDanisch**
@pbouffard, I improved your example to integrate nicely into the gallery, and also added some performance fixes and possibly nicer makie usage. What do you think?

### CODE REVIEW

**Comment by pbouffard** [comment]
Changes look good to me!

**Comment by SimonDanisch** [comment]
This got merged! :D

**Comment by asinghvi17** [comment]
Woops :P

**Comment by SimonDanisch** [comment]
Yeah sorry, I'm not really sure how I pushed it, without auto merging this branch :\

**Pull request closed without merging**
