### PR TITLE
Cheatsheet for Makie.jl

### PR DESCRIPTION
**Pull request by mikolajhojda**
The reference sheet can be useful in the basics. It is a short tutorial. It contains knowledge about some functions, animations, interactions.

### CODE REVIEW

**Comment by asinghvi17** [comment]
This looks really great!  Could you provide a source file as well (how you made it), and maybe move this to `docs/src/assets`?

**Comment by asinghvi17** [comment]
bump @mikolajhojda

**Comment by mikolajhojda** [comment]
Sorry, I didn't see it. I based on http://makie.juliaplots.org/dev/. I created it in Illustrator.

**Comment by mikolajhojda** [comment]
Adnotacja 2020-01-21 204834

**Comment by asinghvi17** [comment]
Could you upload the original Illustrator document as a zip file in a comment on the PR?  That would be perfect, because it would be a lot easier to edit when we break things :).

**Comment by mikolajhojda** [comment]
[makie.zip](https://github.com/JuliaPlots/MakieGallery.jl/files/4097959/makie.zip)

**Comment by logankilpatrick** [comment]
We probably don't want a zip here unless absolutely necessary

**Comment by mikolajhojda** [comment]
Github doesn't support .ai file type.

**Comment by asinghvi17** [comment]
Yeah a zip is fine, this is just for when we have to break stuff anyway :D.  Thanks!

**Pull request merged**
