### PR TITLE
Update Project.toml

### PR DESCRIPTION
**Pull request by asinghvi17**
Fix JuliaPlots/Makie.jl#337 incompat.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
I don't think we should restrict ImageCore to only accept 2 versions... we should in theory accept all versions, since I don't think there is a single ImageCore version that would break Makie... If ImageCore breaks pkg in itself, than we shouldn't fix that in our TOML....

**Comment by asinghvi17** [comment]
I could change it to `≥ 0.5`?

**Comment by SimonDanisch** [comment]
0.5 doesn't even exist :D Why would we constrain it to the the very first version? Isn't that exactly what would happen if we take out the constraint?

**Comment by asinghvi17** [comment]
also, it isn't ImageCore breaking General, but General is breaking itself.  From Metadata, the transition caused constraints which were way too tight.

**Comment by SimonDanisch** [comment]
Ah, so we need to define the constraints, in order to update the constraints in General? -.-

**Comment by asinghvi17** [comment]
We simply need to get the registrator to remove the upper bound, yeah.

**Comment by asinghvi17** [comment]
Actually, >= 0.7 makes more sense, since before that it didn't support 0.7 :D

**Comment by SimonDanisch** [comment]
Thanks!

**Pull request merged**
