### PR TITLE
Added Basic tutorials from plots.jl

### PR DESCRIPTION
**Pull request by Akshat-mehrotra**
implemented the basic tutorial from plots in makie. * marginal histogram and
direct usage of Distributions.jl is not availabe in makie

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Great work!

**Comment by Akshat-mehrotra** [comment]
I don't understand, what's failing in these checks?

**Comment by logankilpatrick** [comment]
Don’t worry too much, there likely needs to be some refactoring anyway.

**Comment by Akshat-mehrotra** [comment]
Okay, I'd be happy to help with anything I can

**Comment by asinghvi17** [comment]
Yeah CI hasn't been green since a long long time, and Travis can't work since it doesn't have a GPU..don't worry about it :D

**Pull request closed without merging**
