### PR TITLE
update image

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by asinghvi17** [comment]
Could it be something with the JuliaGPU mirroring?

**Comment by asinghvi17** [comment]
https://gitlab.com/JuliaGPU/MakieGallery-jl/-/jobs/239722889 is a manually created pipeline that's running fine, so I don't think it's the server?

**Comment by SimonDanisch** [comment]
Ah, it just took some time ;)

**Comment by asinghvi17** [comment]
Great, I didn't mess anything up :P

**Comment by asinghvi17** [comment]
GTM?

**Comment by asinghvi17** [comment]
I think that if the lengths aren't the same, we can just warn, not error - that way you still get the visual regression output of the rest.

**Pull request merged**
