### PR TITLE
Restructure examples

### PR DESCRIPTION
**Pull request by asinghvi17**
Right now, the DifferentialEquations.jl examples are in a lot of different places.  This PR will concentrate them into one file, which could then be optionally included or excluded.  This could allow us to avoid including DifferentialEquations.jl as a test dependency (which currently breaks precompilation because of some errors in its dependencies).

### CODE REVIEW

**Comment by asinghvi17** [comment]
@SimonDanisch, what do you think of the change?

**Comment by SimonDanisch** [comment]
Yeah why not, thanks :)

**Comment by SimonDanisch** [comment]
You didn't update the database to include the new file yet, did you?

**Comment by asinghvi17** [comment]
Oops :)

**Comment by asinghvi17** [comment]
Done now...no new examples in this one, only a restructure, so I _think_ it's OK?

**Pull request merged**
