### PR TITLE
add docs for theming

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Well, that `or` is exactly why I chose the Julia way to describe it ;)

**Comment by asinghvi17** [comment]
Makes sense, it is more flexible...still, it does take a while to parse :)

**Comment by asinghvi17** [comment]
Oh, looks like that example of color legend theming I'd added a while ago is failing.  @SimonDanisch any idea why?  It's failed both times it was CI'ed, with the error message being 
```julia
/builds/JuliaGPU/MakieGallery-jl/.julia/packages/MakieGallery/gtWNT/test/test_recordings/line_with_varying_colors: Test Failed at /builds/JuliaGPU/MakieGallery-jl/.julia/packages/MakieGallery/gtWNT/src/testruns.jl:107
  Expression: diff <= maxdiff
   Evaluated: 0.05773504474405718 <= 0.03
Stacktrace:
 [1] macro expansion at /builds/JuliaGPU/MakieGallery-jl/.julia/packages/MakieGallery/gtWNT/src/testruns.jl:107 [inlined]
 [2] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
 [3] macro expansion at /builds/JuliaGPU/MakieGallery-jl/.julia/packages/MakieGallery/gtWNT/src/testruns.jl:94 [inlined]
 [4] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
 [5] #run_comparison#126(::Float64, ::Function, ::String, ::String, ::String) at /builds/JuliaGPU/MakieGallery-jl/.julia/packages/MakieGallery/gtWNT/src/testruns.jl:85
Test Summary:                                                                                                                                                                    | Pass  Fail  Total
Reference Image Tests                                                                                                                                                            |  184     1    185
```

**Comment by asinghvi17** [comment]
Might be because the width of the color legend is hardcoded but the dimensions of the `Scene` aren't?

**Comment by SimonDanisch** [comment]
unlikely... i'll take a look! but note, that makiegallery master is kind of expected to fail, since im only updating reference images when tagging;)

**Comment by SimonDanisch** [comment]
`line_with_varying_colors` fails, which is because you updated it to look better :)

**Comment by asinghvi17** [comment]
That makes sense :) ... I thought the reference images were regenerated automatically.

**Pull request merged**
