### PR TITLE
Update examples2d.jl

### PR DESCRIPTION
**Pull request by musm**
The current example doesn't actually work.

Also how can I change the padding to zero?

### CODE REVIEW

**Comment by musm** [comment]
@SimonDanisch  any help on this?

**Comment by SimonDanisch** [comment]
Oh sorry, you're right...this looked pretty fishy to me, since tests were passing - but it does the wrong thing after all... Let me have a look, since this should definitely be working!

**Comment by SimonDanisch** [comment]
Ok, this was a regression:
https://github.com/JuliaPlots/AbstractPlotting.jl/commit/ea678e06384156b71ad3e539e3bb6db0ed3476c4
Damn it, seems like my tests were not working anymore -.-

**Comment by SimonDanisch** [comment]
Indeed, the wrong test image has sneaked in:
https://github.com/SimonDanisch/ReferenceImages/blob/master/gallery/customize_axes/media/image.jpg

**Comment by musm** [comment]
I see, so  should I close this or...?

**Comment by musm** [comment]
BTW is indexing  as in
`axis.grid.linewidth = (0, 0)` 
the prefered way to make modifications to properties?

**Comment by SimonDanisch** [comment]
```
BTW is indexing as in
`axis.grid.linewidth = (0, 0)`
the prefered way to make modifications to properties?
```
Yeah, for modifications that should be preferred!

**Pull request closed without merging**
