### PR TITLE
Add precompilation instructions to docs

### PR DESCRIPTION
**Pull request by asinghvi17**
It seems like a lot of people aren't seeing the `Precompilation` section on Makie's README, and I figured we'd need it in the docs anyway, so it makes sense to add it now.  I'm also trying to add a workflow to cope with segfaults in the building process that can occur sometimes.

### CODE REVIEW

**Comment by asinghvi17** [comment]
@SimonDanisch this should be ready for checks!  No examples added here, just some text.

**Comment by SimonDanisch** [comment]
Thank you, looks like it covers everything! :) 
This is slightly wrong though:
```
If you plan to develop Makie, it is impossible to do so using statically compiled Makie, because the functions are baked into the system image. 
```
It is possible, but only during one session! So any file changes will not get updated the next time you start julia - but could just go in there with Atom and manually evaluate the changed files ;)

**Comment by asinghvi17** [comment]
Fixed, thanks!

**Comment by SimonDanisch** [comment]
Thanks a lot :)

**Pull request merged**
