### PR TITLE
Document recipes

### PR DESCRIPTION
**Pull request by asinghvi17**
I've copy-pasted the recipe documentation from AbstractPlotting into a file in MakieGallery. Since I didn't actually add anything, I want to put Simon and Chris as co-authors (they seem to be the ones who wrote the actual documentation.

This isn't nearly done yet, so if you're reading this and have some more documentation to add, please comment!

### CODE REVIEW

**Comment by SimonDanisch** [comment]
It doesn't need to be fully done yet, since the recipe system isn't 100% stable yet, so we shouldn't put too much time into it right now ;)

**Comment by asinghvi17** [comment]
Fair enough :) I just saw some low hanging fruit here since there seems to be some Recipe documentation in `AbstractPlotting`, not sure if that's still correct though.  Maybe we could update this as the recipe system changes?  It would be nice just to have it as reference here.

**Comment by asinghvi17** [comment]
Since there seems to be a lot of confusion around `Recipe`s, could we get at least a brief overview of how it actually works?

**Comment by asinghvi17** [comment]
There is still a little confusion around how series works...I believe @piever was working on something, but I'm not exactly sure how one might use that.  Once that's introduced, though, I think this should be a decent introduction to recipes...for what we have now, at least.

**Pull request merged**
