### PR TITLE
Update why-makie.md

### PR DESCRIPTION
**Pull request by logankilpatrick**
Added a little bit more about what makes up the makie ecosystem. I think that the "Why Makie" section is an important place to talk about what actually makes it up.

### CODE REVIEW

**Comment by logankilpatrick** [comment]
This is a hybrid of ```https://github.com/JuliaPlots/Makie.jl```

**Comment by asinghvi17** [comment]
I agree that this should be in the docs, however a better place for it would probably be under the `Home` section.  Perhaps a section about the ecosystem would be appropriate there?

**Comment by logankilpatrick** [comment]
Makes sense to me. I will update later today. 

Best, 
Logan Kilpatrick

**Comment by logankilpatrick** [comment]
Closed in favor of #103

**Pull request closed without merging**
