### PR TITLE
snake tutorial

### PR DESCRIPTION
**Pull request by jkrumbiegel**
I tried to make a basic tutorial based on the previous snake examples that explains basic observables and a bit of interaction to spark people's interest and get them started. The assets are not auto-generated as I didn't figure out how that would work with resizing of the window. Would of course be nicer if that was not something you'd have to repeat manually at some point.

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
Also the asset paths should be wrong now, someone who knows how the system here is set up can change them easily

**Comment by asinghvi17** [comment]
Looks good, thanks!  We should add the snake example to the Gallery, so that it can be autorecorded in the future.

Let me know when you're done with the PR, and I can work on getting this integrated with the gallery.  I _believe_ there is a `MakieGallery.assetpath()` which should give you a standardized location to put assets in.

**Comment by asinghvi17** [comment]
Just got to reviewing this fully.  I'll also make this an example in the Gallery, located in a file which is not included by default (so it doesn't get run during tests); that way, we can show the finished product as well.

I believe you might have to refer to assets as `assets/snake_tutorial/...` when including them.

**Comment by SimonDanisch** [comment]
Does this work already as part of the docs and is ready to merge?

**Comment by asinghvi17** [comment]
I would like to add it as an example in the gallery, so we can remove the directory.  There's still some cleanup to do here, though.

**Pull request closed without merging**
