### PR TITLE
Corrected bug in colormaps example

### PR DESCRIPTION
**Pull request by ianshmean**
As discussed in https://github.com/JuliaPlots/Makie.jl/issues/255

### CODE REVIEW

**Comment by SimonDanisch** [comment]
thanks :)

**Comment by SimonDanisch** [comment]
let me merge this a bit later, since the current tests rely on MakieGallery, so this will make the tests fail ;)
I'll need to update the reference images first!

**Comment by ianshmean** [comment]
Ok!

**Comment by SimonDanisch** [comment]
Thanks a lot! :)

**Pull request merged**
