### PR TITLE
Add robot arm example

### PR DESCRIPTION
**Pull request by pbouffard**
As discussed over at https://github.com/JuliaPlots/Makie.jl/issues/307. Output should look like https://giphy.com/gifs/25JgIK6v56kKIi7CsG (I'm not sure how to go about including a video in the gallery).

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Ah, you're fast! Sorry, I took the freedom to already add the examples locally and trying to get tests pass right now, with recorded events etc... 
I also added the earth example :D 
I'll link you once it works! Let me know if I reference you correctly!

**Comment by SimonDanisch** [comment]
Ok, this is part of https://github.com/JuliaPlots/MakieGallery.jl/pull/18 now! Hope it's okay that you're not in the commit, and just referenced like [this](https://github.com/JuliaPlots/MakieGallery.jl/blob/3ae56369cb360812a34fcdc554f49b51685ebc4a/examples/interactive.jl#L304)^^ Otherwise feel free to recommit or something ;)
I also cleaned up the examples a bit, to make them more idiomatic!

**Comment by SimonDanisch** [comment]
They can now be found via the [gallery](https://simondanisch.github.io/ReferenceImages/gallery/index.html):
https://simondanisch.github.io/ReferenceImages/gallery//earth___ships/index.html
https://simondanisch.github.io/ReferenceImages/gallery//robot_arm/index.html

**Comment by SimonDanisch** [comment]
Oh wow, the html display rips out the comments about your authorship :-O
That of course needs fixing ;)

**Comment by pbouffard** [comment]
Cool, thanks for including this!

**Pull request closed without merging**
