### PR TITLE
Update labeler.yml

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by asinghvi17** [comment]
doesn't seem working @logankilpatrick ... does it have to be merged into master first?

**Comment by logankilpatrick** [comment]
Yes! 

Best, 
Logan Kilpatrick

**Comment by asinghvi17** [comment]
Cool, thanks.

**Comment by logankilpatrick** [comment]
Worth noting that, https://github.com/actions/labeler/issues/12, seems to indicate that the labeler will fail when a non-maintainer opens a PR due to issues with read/write access tokens only being accessible to maintainers.

**Pull request merged**
