### PR TITLE
Switch to using the cell method

### PR DESCRIPTION
**Pull request by asinghvi17**
Wanted your advice on this, all - compare http://makie.juliaplots.org/previews/PR223/statsmakie.html with http://makie.juliaplots.org/previews/PR224/statsmakie.html

### CODE REVIEW

**Comment by SimonDanisch** [comment]
The second url is 404 ;)

**Comment by asinghvi17** [comment]
Oh...my bad, the doc build doesn't run on PRs not targeting master

**Comment by piever** [comment]
Concerning the StatsMakie doc, now I think the situation is a bit unclear, as there is an "untested" version [here](http://juliaplots.org/StatsMakie.jl/latest/manual/tutorial/), as well as a tested version [here](http://makie.juliaplots.org/dev/statsmakie.html). Should we just remove the doc page from StatsMakie in favor of unified documentation?

**Comment by SimonDanisch** [comment]
I'm for: http://makie.juliaplots.org/previews/PR223/statsmakie.html

>Concerning the StatsMakie doc, now I think the situation is a bit unclear, as there is an "untested" version here, as well as a tested version here. Should we just remove the doc page from StatsMakie in favor of unified documentation?

https://github.com/JuliaPlots/AbstractPlotting.jl/issues/349
I want to move docs to the packages that are responsible for it and test them there...And then just collect them here to also have a central place for makieverse!

**Comment by jkrumbiegel** [comment]
also #223, the other one cuts off a lot of code for me

**Comment by piever** [comment]
> I want to move docs to the packages that are responsible for it and test them there...And then just collect them here to also have a central place for makieverse!

I see, so the way forward is https://github.com/JuliaPlots/StatsMakie.jl/issues/100.

Concerning the two options, I find 223 much nicer.

**Comment by asinghvi17** [comment]
Sounds good - this was just a small alternative I wanted to explore to shorten the page size, but I agree that it doesn't show long code well.  I've already merged #223, so will just close this.

**Pull request closed without merging**
