### PR TITLE
Add docs about known errors and troubleshooting a Makie install

### PR DESCRIPTION
**Pull request by asinghvi17**
Ref: JuliaPlots/Makie.jl#307

This PR aims to reduce the number of duplicate issues reported, and to smoothen the installation process.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Thank you! :)

**Comment by asinghvi17** [comment]
Note to self: reference JuliaGeo/GDAL.jl#180

**Comment by SimonDanisch** [comment]
Hopefully that is soon fixed by: 
https://github.com/JuliaGL/GLFW.jl/pull/147

**Comment by asinghvi17** [comment]
I think this should be pretty much good for merge @SimonDanisch!  Do give it a look

**Pull request merged**
