### PR TITLE
Add flexibility in database loading

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by asinghvi17** [comment]
@SimonDanisch tests work on my end, would you mind trying out the new functions on your end as well?

**Comment by asinghvi17** [comment]
Merging in 12 hours.

**Comment by SimonDanisch** [comment]
ah, btw i didnt test my changes at all :'( really bad practise :-D

**Comment by asinghvi17** [comment]
None of these changes *should* have broken anything ;P

**Pull request merged**
